flowchart LR
  classDef objeto fill:#E8FFF5,stroke:#007B5F,stroke-width:3px,color:#14212B;
  classDef objeto2 fill:#D9FFF0,stroke:#00B388,stroke-width:3px,color:#14212B;
  classDef correlato fill:#EAF6FC,stroke:#0067A0,stroke-width:2px,color:#14212B;
  classDef apoio fill:#FFF5C7,stroke:#FFCD00,stroke-width:2px,color:#14212B;

  U1["Unidades TRT10<br/>MPLS 1 Gbps: Sede e Foro<br/>MPLS 500 Mbps: Apoio, Taguatinga, Palmas<br/>MPLS 100 Mbps: Gama, Araguaína, Gurupi, Dianópolis, Guaraí"]:::objeto
  MPLS["Rede MPLS contratada<br/>10 circuitos<br/>capacidade igual à SD-WAN vigente"]:::objeto
  SEDE["SEDE<br/>MPLS 1 Gbps<br/>Internet 3 x 4 Gbps<br/>Anti-DDoS + 32 IPs por link"]:::objeto
  FORO["FORO DE BRASÍLIA<br/>MPLS 1 Gbps<br/>Internet 2 x 2 Gbps<br/>Anti-DDoS + 32 IPs por link"]:::objeto
  L25["Link dedicado Sede-Foro<br/>25 Gbps ponto-a-ponto<br/>não MPLS"]:::objeto2

  I12["Item 12<br/>Internet Sede 1<br/>4 Gbps / Anti-DDoS / 32 IPs"]:::objeto2
  I13["Item 13<br/>Internet Sede 2<br/>4 Gbps / Anti-DDoS / 32 IPs"]:::objeto2
  I14["Item 14<br/>Internet Sede 3<br/>4 Gbps / Anti-DDoS / 32 IPs"]:::objeto2
  I15["Item 15<br/>Internet Foro 1<br/>2 Gbps / Anti-DDoS / 32 IPs"]:::objeto2
  I16["Item 16<br/>Internet Foro 2<br/>2 Gbps / Anti-DDoS / 32 IPs"]:::objeto2

  SDWAN["SD-WAN vigente<br/>camada correlata de transporte e contingência"]:::correlato
  APOIO["Firewalls, DNS, autenticação,<br/>Infovia, redes JT e monitoramento"]:::apoio

  U1 --> MPLS --> SEDE
  MPLS --> FORO
  SEDE <--> L25 <--> FORO
  I12 --> SEDE
  I13 --> SEDE
  I14 --> SEDE
  I15 --> FORO
  I16 --> FORO
  U1 -.-> SDWAN -.-> SEDE
  SDWAN -.-> FORO
  APOIO -.-> SEDE
  APOIO -.-> FORO
